// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDinnv4hxA-rx0TO-6dNRKIEZKcsym6sz8',
    appId: '1:1022454168681:web:21519d459c4b63d700f6f8',
    messagingSenderId: '1022454168681',
    projectId: 'toddy-1d800',
    authDomain: 'toddy-1d800.firebaseapp.com',
    storageBucket: 'toddy-1d800.appspot.com',
    measurementId: 'G-7D28492VZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZhu15v4yEeOY7pAmkopLAdiek7BZfUYc',
    appId: '1:1022454168681:android:dea108e547ad0d7a00f6f8',
    messagingSenderId: '1022454168681',
    projectId: 'toddy-1d800',
    storageBucket: 'toddy-1d800.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-Y9mZGBc8DQ3Hs0UdZ3IZPT4UQQ_SoU0',
    appId: '1:1022454168681:ios:936454a27c705b6200f6f8',
    messagingSenderId: '1022454168681',
    projectId: 'toddy-1d800',
    storageBucket: 'toddy-1d800.appspot.com',
    androidClientId: '1022454168681-0c012985eeo0q7ukga95611ookckhsq9.apps.googleusercontent.com',
    iosClientId: '1022454168681-4b3pcpqviot0nhmhb9b92h52jq916cer.apps.googleusercontent.com',
    iosBundleId: 'com.temaandone.toddyapp',
  );
}
